const ActionTypes = {
    USERNAME:'USERNAME',
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    LOGIN: 'LOGIN',
}

export default ActionTypes;